src/log.h
When logging to stderr, telem_perror output is incomplete and badly
formatted. Print errno correctly, fix newline and fix includes.
Signed-off-by: Jeremy Rocher <jeremy.rocher@intel.com>
=> fix telem_perror when logging to stderr

src/probes/crash_probe.c
stderr could be used for logging or in libtelemetry in DEBUG mode but
when crashprobe is launched through kernel core_pattern, stderr is not
open, only stdin (fd 0), see this dump from gdb:
(gdb) shell ls -l /proc/15478/fd
total 0
lr-x------ 1 root root 64 24 juin  15:02 0 -> pipe:[82555]
If stderr is not open, when socket to telemd is open it could take
fd 2 and in this case all fprint to stderr are written to socket which
is bad ... this is the case when doing static linking, which ends to
telemd crashed.
Fix it by ensuring stderr is open.
Signed-off-by: Jeremy Rocher <jeremy.rocher@intel.com>
=> crashprobe: fix stderr when launched from kernel

configure.ac
It's often useful to print a summary of configuration options for the
build, so add a AC_MSG_NOTICE() to the tail end of the configure script.
=> build: echo build configuration for configure

src/probes/crash_probe.c
Missing symbols in backtraces might indicate missing debuginfo from the
crashed program, but another possibility is that on-the-fly debuginfo
has not finished downloading. The Clear Linux OS uses an on-the-fly
debuginfo setup, so this condition is likely for the first instance of a
program crashing on the system.
To decrease likelihood of missing symbols appearing, scan the backtrace
for a frame with incomplete data after first processing, and if found,
reprocess the core file after a 10 second pause.
=> crash probe: retry processing when missing symbols

src/probes/crash_probe.c, src/probes/local.mk, src/probes/oops_parser.c, src/probes/probe.h
There are some filters in place that prevent probes from collecting
specific types of data. In particular, the oops probe will report "zero"
or "non-zero" for register values in oopses instead of the actual
values. And the crash probe does not send backtraces if binaries live
outside of `/usr` or under `/usr/local`.
This commit keeps these filters in place but offers the capability to
disable the filters by creating a file named
```
/etc/telemetrics/opt-in-no-privacy-filters
```
Any future telemetry privacy filters can check for this file to alter
the reporting level.
=> Add opt-in feature to disable privacy filters

src/probes/journal.c
This series reworks the existing journal probe to make it more generic, able to capture error log messages for any service, not just the crashprobe.
=> Journal probe rework

src/probes/oops_parser.c, tests/check_probes.c, tests/oops_test_files/bug_kernel_handle_new.txt
The Linux 4.10 release introduced some changes to the oops format, so the oops parsing code needs an update.
=> Support new oops format

src/telemdaemon.c
When the daemon is sitting idle, we are seeing libcurl consume around
2MB of memory, which had been previously allocated on-the-fly for its
global environment.
To have more control over this memory consumption, making sure the
daemon uses as little memory as possible when doing no work, explicitly
allocate the libcurl global environment before each POST and deallocate
it afterwards.
=> Init/deinit libcurl global environment for each POST

src/probes/crash_probe.c
When the path filters for privacy are in effect, backtraces are scrubbed from records, and this results in the core files being unlinked.
However, this is not friendly behavior for the developer. A common situation that triggers the path filters is installing custom binaries on the system (say, under /usr/local/bin or /opt/bin) for testing purposes. To better enable developers to debug their programs, having the core files available to process with gdb is very valuable.
Eventually, I would like to add an opt-in to keep all core files, but I'll wait until the configuration code is refactored.
=> crash probe: keep core files under certain conditions

src/configuration.c
There was a regression introduced in the port to libnica that resulted in a segfault. Fix that issue, and make the error reporting more verbose and thus more actionable.
=> Fix regression in configuration parsing

src/common.h
Record format has to be bumped since the record changed with the addition of metadata.
=> Bumping record format version to 3

README.md
Because the telemetrics-backend repo is now hosted on Github, link to it
from the client README, since it is part of a complete telemetrics
solution.
=> Link to telemetrics-backend repo from the README

src/configuration.c, src/telemetry.c
The call to "fprint()" is a typo and should be "fprintf()".
Also, the "error->message" string is an artifact from the time when
telemetrics-client used glib. Now it uses libnica, which propogates
errors differently. Simply remove the format specifier for now.
=> Fix build issues when -DDEBUG is enabled

src/telemdaemon.c
`readv` is declared in <sys/uio.h>
=> Fix compiler warning

src/probes/hello.c
Parameter config_file is named incorrectly in opts array.
=> Fixing config parameter in hprobe

configure.ac, tests/local.mk
Added source files references to local.mk and headers files
to check_libtelemetry to compile client in gcc 8 and CFLAGS
-flto. This change fixes an error when compiling and running
tests where the resulting binary is unable to find symbols.
This is a workaround and has to be fixed properly.
=> Changes to compile check_libtelemetry with flto

src/probes/crash_probe.c
It is possible that transient errors may be raised when processing the core file, so speculatively retry for any processing errors that appear for the first run.
NOTE: currently untested
=> crash probe: retry processing when errors occur

src/probes/telem_record_gen.c, src/telemetry.c
Multiple improvements and fixes to telem record gen probe.
* Adding a print option to telem-record-gen to print metadata and record payload. Additionally remove option that is not implemented.
* Fixing detected memory leak.
* Remove return carriage that should not be present in model name header.
=> Improvements and fixes to telem-record-gen

src/probes/telem_record_gen.c
This change fixes a bug where the telem-record-gen probe returns 1
though the execution of the probe was successful. This bug was
introduced when print message option feature was implemented.
=> Fix telem-record-gen bug in send_record condition

src/telempostdaemon.c, src/telempostdaemon.h, tests/check_postd.c
The following changes are:
* Logic to retry sending telemetry messages when during boot network was not available.
* Moving block of code in telempostdaemon to logically related branch.
This PR is partially a port of [PR/72](https://github.com/clearlinux/telemetrics-client/pull/72) due to refactoring PR/72 was not longer applicable.
=> Post retry when not network available at boot

src/probes/telem_record_gen.c
When opt-out is enabled, the instanciate_record() function will return
-111 and the headers will not be allocated. Since print_record only
checks that instanciate_record does not return -1 before trying to go
through the headers, a segfault will occur.
This can be seen via:
$ sudo touch /etc/telemetrics/opt-out
$ telem-record-gen -c a/b/c -o -n -p 'payload goes here'
=> probes/telem_record_gen.c: fix possible segfault in print_record

src/common.h, src/probes/bert_probe.c, src/probes/telem_record_gen.c
The file common.h contained two definitions to specify the
maximum allowable payload:
define MAX_PAYLOAD_SIZE 8192
define MAX_PAYLOAD_LENGTH 8192
This patch removes the definition for MAX_PAYLOAD_SIZE and replaces all
occurences of MAX_PAYLOAD_SIZE with MAX_PAYLOAD_LENGTH.
=> Remove redundant definition MAX_PAYLOAD_SIZE

docs/man/telem-record-gen.1, docs/man/telemctl.1, docs/man/telemetrics.conf.5, docs/man/telemetry.3, docs/man/telempostd.1, docs/man/telemprobd.1
The .rst were updated. All man pages need to be rebuilt/updated as well.
(Mostly removing/replacing "telemd" references)
=> man pages: update

src/probes/bert_probe.c
There is no entry for 'H' command line option, yet the
getopt_long accepts it as a valid option.
=> bert_probe.c: remove unsupported cmdline option

scripts/telemctl
This change fixes a bug where the oops probe and journal probe are not
restarted when telemctl restart is executed.
=> Fix for missing restart units

docs/man/telemetry.3, docs/man/telemetry.3.rst, src/configuration.c, src/configuration.h, src/local.mk, src/post.c, src/probe.c, src/probes/bert_probe.c, src/probes/crash_probe.c, src/probes/hello.c, src/probes/journal.c, src/telemetry.c, src/telemetry.h
This change was on a TODO list for a few years.
The function tm_set_config_file could silently fail as it did not
return any status. This forced implementing of all error checks by
the callers of this function.
The current implementation does its own error checks and string copying.
The function returns an error code if errors were encountered.
Since this is a library function, all callers needed to be modified as well.
However, the modifications are code simplifications so this is not too painful.
In addition, the change also affected library documentation as well (void -> int).
As a direct consequence, this change allows simple implementation of the command
line argument "--config_file" uniformly across all probes.
=> tm_set_config_file: return status and call from all probes

scripts/telemctl, src/data/local.mk, src/data/python-probe.path.in, src/data/telemetrics-dirs.conf.in, src/probes/python-probe.c
Don't wait for new payload via inotify, let systemd path unit
detect any new payloads in /usr/lib/telemetry/python and start
the pythonprobe service.
Also set the sticky bit for the above folder, preventing users to
modify permissions.
=> pythonprobe: don't use inotify

.gitignore, src/probes/crash_probe.c
In modern times, the default core_pattern for Clear Linux OS is set to
```
|/usr/lib/systemd/coredump-wrapper %E %P %u %g %s %t %c %h %e
```
This wrapper script sends core files to both systemd-coredump and crashprobe (if installed).
Because systemd-coredump will store core files in the systemd journal, there is no longer a strong reason to preserve the crashprobe core files in /tmp, aside from when crashprobe's --core-file option is used. If developers wish to access core files, they can use `coredumpctl` instead to extract them from the systemd journal.
=> crashprobe: always remove core files, except when passing --core-file

src/probes/hello.c
Optionally add locale, uptime and list of installed bundles
to the payload. The default behavior is as before.
Additional payload is can be enabled via cmd line arguments:
-l : add locale info
-b : add installed bundles info
-u : add uptime info
For consistency, always use telem_log(LOG_ERR,...) instead
of fprintf(stderr,...).
=> hello.c: additional payload content

scripts/telemctl, src/data/journal-probe-tail.service.in, src/data/local.mk, src/probes/journal.c
This adds an optional argument to journalprobe that allows seeking to
the end of the journal. This is then used in a new service file that is
called by telemctl on restart. This allows us to scan the entire journal
on boot, and only scan new journal entries when restarting, or opting
into telemetry manually. This reduces spam from repeated messages and
fixes a possible privacy concern, as previously running telemctl start
could include journal errors that occurred before telemetrics was opted
into.
=> journalprobe: don't process entire journal on restart

src/data/python-probe.path.in, src/data/telemetrics-dirs.conf.in
Python3 expects two "well known" folders to exist in order to generate exception
payloads:
/var/tmp/telemetry
/var/lib/telemetry/python
Both folders must exist at the above absolute locations in order to properly
create and submit Python3 telemetry unhandled exception payload.
=> pythonprobe: fix folders

src/spool.c
In case of memory allocation failures or record parsing failures,
"transmit_spooled_record" may have returned without freeing any previously
allocated memory.
=> spool.c: fix memory leak

src/common.h, src/configuration.c, src/configuration.h, src/iorecord.c, src/iorecord.h, src/post.c, src/spool.c, src/telemdaemon.c, src/telemetry.c, src/telempostdaemon.c, src/telempostdaemon.h, tests/check_postd.c
Most probes allow passing of non-default configuration file
via command line using the "-f" switch.
For example:
$ hprobe -f custom_cfg_file.conf
If the file "custom_cfg_file.conf" contains
server = http://<my backend server>
one would expect the hprobe payload will be sent to the server
http://<my backend server>. However, this is not the case, as the
various daemons delivering the payload to the backend are blissfully
unaware of the of the config file hprobe wanted to use.
The solution is to include the absolute path of the config file
specified on the command line as part of the payload. Once the
payload is about to be sent via the routine "post_record_http",
the routine checks if a non-default config file was requested.
If so, configuration is re-initialized with the file.
Upon exit, …
=> Improve support of non-default configuration files.

build-aux/make/cflags.make, configure.ac, src/configuration.c, src/configuration.h, src/data/example.2.conf, src/data/local.mk, src/data/telemetrics.conf.in, tests/check_config.c
Have a default configuration set in the binary, with conf files only
being used to change from the defaults. This allows making simpler
configs which only toggle specific options, which may be useful for user
configuration or testing. See src/data/example.2.conf for an example of
a new simplified config.
The default backend server can be changed via the configure flag
--with-backendserveraddr=URI. This allows anyone else using this project
to easily specify their own default backend without patching.
=> configuration: rework to allow layered configuration

src/iorecord.c, src/iorecord.h, src/local.mk, src/post.c, src/probe.c, src/telemdaemon.c, src/telemdaemon.h, src/telempostdaemon.c, src/telempostdaemon.h, tests/check_postd.c, tests/check_probd.c
The telempostd and telemprobd daemons both used identical
name "initialize_daemon" for daemon initialization.
Although the name was identical, the code for each daemon initialization
was different, leading to some potential confusion.
Also moved telemprobd specific code "stage_record" from iorecord.c to
telemdaemon.c
Modified local.mk accordingly.
=> daemons: name space separation

src/post.c, src/probe.c
Moved a misplaced comment to where it belongs.
Fixed incorrectly formatted log string.
=> Minor houskeeping

build-aux/make/cflags.make
Compiler optimization can remove certain security checks for undefined
behavior. Add compiler flags that restrict arbitrary decisions when
handling undefined behaviors.
* fno-strict-overflow, do not assume signed overflow does not occur.
* fno-delete-null-pointer-checks, do not assume null pointer deference
does not exists.
* fwrapv, always wrap signed overflow.
Signed-off-by: Alex Jaramillo <alex.jch@gmail.com>
=> Protect security checks from removal

tests/check_probes.c
Replaced strncpy with memcpy and added some buffer overflow checks in
order to avoid GCC9 compiler warning:
warning: ‘__builtin___strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
While in there, removed one unused global variable and declared the remaining
global variables as static.
=> check_probes.c: fix for compiler warning [-Wstringop-overflow=]

src/probes/telem_record_gen.c
Replace strncpy with memcpy to avoid GCC9 warning:
warning: ‘__builtin___strncpy_chk’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
There is no danger of overflow. The destination buffer is guaranteed to
be of MAX_PAYLOAD_LENGTH.
=> telem_record_gen.c: fix for compiler warning [-Wstringop-overflow=]

src/probes/klog_scanner.c, src/telemetry.c
Modify code to avoid generating compiler warning such as:
warning: ‘__builtin_strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
=> Fix compiler warnings [-Wstringop-truncation]

configure.ac
Version bump from 2.1.1 to 2.2.0
=> configure.ac: bump version to 2.2.0

src/journal/local.mk, src/log.h, src/probes/local.mk, tests/local.mk
Build is broken for multiple binaries when configured for logging
to systemd journal:
$ ./configure --enable-logtype=systemd
$ make
All binaries that use the routine "telem_log" must link to additional
libraries when logging to systemd journal.
=> Fix build for logtype=systemd

docs/man/telem-record-gen.1, docs/man/telem-record-gen.1.rst, docs/man/telemctl.1, docs/man/telemctl.1.rst, docs/man/telemetry.3, docs/man/telemetry.3.rst
"telemd" was replaced by "telemprobd" a long time
ago, however several man pages still contain refererences
to "telemd".
This patch replaces all references accordingly.
=> man pages: remove references to telemd

src/probes/oops_parser.c
If "ACPI Error:" happen, it means there is kernel or bios issue.
Signed-off-by: Ammy Yi <ammy.yi@intel.com>
=> Add "ACPI Error:" pattern for ACPI issues.

src/journal/journal.c
Causing double free case when an empty line has been
passed to deserialize_journal_entry() from print_journal()
to print the report, This case double free can be occured
at print_journal() and deserialize_journal_entry().
=> Fix double free in deserialize_journal_entry() and print_journal()

src/util.c
Even if errors were encounterd parsing the header we used to
return success ("true") by a mistake.
Fix this by correcting the test.
=> util.c: correct return value from "get_header_value"

src/telemdaemon.c
"fscanf" assumes an arbitrarily long string, so limit the scan to
32 characters to avoid a potential buffer overflow.
=> telemdaemon.c: don't assume correct machine_id length

src/probes/telem_record_gen.c
In the routine "instanciate_record":
If the user passed event_id on the command line and it was incorrect,
any returned error from tm_set_event was ignored and "instanciate_record"
could return success (0).
=> telem_record_gen.c: return correct error in instanciate_record

src/probes/telem_record_gen.c
It is allowed to enter the same command line argument more than once,
the later value overriding the previous one.
Make sure any previous value is properly de-allocated.
=> telem_recorde_gen.c: fix potential memory leaks

src/telemdaemon.c
If mkstemp fails, it returns a negative value (-1).
So adjust the test accordingly. Also don't attempt to close
an invalid file descriptor. Don't unlink a file that failed
to be created.
=> telemdaemon.c: properly handle mkstemp error

src/probes/oops_parser.c
Remove a useless test.
Routine "stack_frame_append": don't test again if a pointer
is NULL. It has been done already. Also, the pointer was
already dereferenced before the test.
=> oops_parser.c: remove unneeded check

src/telemdaemon.c
In the routine "machine_id_replace" replace "strcpy" with
a safer "strncpy".
Also declare the routine as static as it is not used outside
of this file.
=> telemdaemon.c: fix for a potential string overflow

src/telempostdaemon.c
"save_entry_to_journal": fix potential freeing of uninitilized
variables.
=> telempostdaemon.c: avoid freeing of uninitialized variables

src/telemetry.c
tm_set_event_id: if a record exists, then the record headers
array exists as well as it is a part of the record itself.
=> telemetry.c: remove unneeded test

src/telemctl.c
Close a file descriptor for a freshly created & opened file
when not needed.
=> telemctl.c: fix resource leak

src/iorecord.c
Prevent time of check to time of use exploit.
Don't use "stat" to get the file size. The "stat" and "fopen"
could refer to two different files.
=> iorecord.c: fix a potential race

src/probes/oops_parser.c
Add pattern for kernel panic. The new pattern can be tested with:
$ sudo sh -c "echo 'c' > /proc/sysrq-trigger"
The above command will crash the system immediately, however upon reboot
the pstoreprobe will send the crah report.
=> oops_parser.c: detect kernel panic

src/probes/oops_parser.c
Remove a test for a valid pointer. The test hase been done
already. Also the pointer has been dereferenced already.
=> oops_parser.c: remove unneded check

src/probes/telem_record_gen.c
Routine "print_record": always call tm_free_record before
exiting the routine.
=> telem_record_gen.c: fix a potential resource leak

src/telemctl.c
Don't use fscanf in order to avoid a potential string overflow.
Use code that is aware of allocated buffer sizes.
=> telemctl.c: avoid using fscanf

src/journal/journal.c
1. Return a known (NULL) value of "*entry" if the function fails.
2. Remove some dead code. Since the loop index ranges 0..4, it is
pointless to have a switch statement outsized of this range.
3. Ensure all pointers within the allocated structure JournalEntry
are defined. (They are initialized as NULL courtesy of calloc),
otherwise we may end up freeing some random pointers in
"free_journal_entry"
=> journal.c: deserialize_journal_entry fixes

src/iorecord.c, src/probes/telem_record_gen.c, src/telemetry.c
Currently if telemetry is opt-out telem-record-gen is unable to print a telemetry message even when no message delivery takes place. This change enables to create messages for printing to stdout.
=> telem-record-gen enable print message

src/probes/telem_record_gen.c
Removed the last error test from routine "instanciate_record".
=> telem_recoder_gen.c: remove redundant if statement

src/telempostdaemon.c
Upon (error) exit the field buf.st_blocks may contain garbage.
Make sure buf.st_blocks is deterministic.
While in there, also removed some redundant round brackets.
=> telempostdaemon.c: fix unitialized variable

src/probes/crash_probe.c
Routine frame_cb: if asprintf fails, assume destination string
is not initialized properly.
=> crash_probe.c: improve error handling

configure.ac
Version bump from 2.2.1 to 2.2.2
=> configure.ac: bump version to 2.2.2

src/data/bert-probe.service.in, src/probes/bert_probe.c
Fix a reported problem: https://github.com/clearlinux/telemetrics-client/issues/170
This patch fixes the case when there is no error reported via BERT data
and yet the probe fails with error such as:
"Failed to read payload from: /sys/firmware/acpi/tables/data/BERT"
Which then results in journalprobe reporting:
"bert-probe.service: Main process exited, code=exited, status=1/FAILURE"
The file BERT data file now has root only read permissions:
$ ls -al /sys/firmware/acpi/tables/data/BERT
-r-------- 1 root root 32768 Nov 25 07:37 /sys/firmware/acpi/tables/data/BERT
Hence the user "telemetry" cannot read it anymore. In addition, the file size
can be more than max payload size (4k). However, the file can be completely
blank. The probe inspects the block_status for any present errors.
If there …
=> bertprobe: fix failures and logging

src/probes/klog_scanner.c
Payloads can exceed MAX_PAYLOAD_SIZE, in which case the probe
will fail to send any data to the backend server. This was observed
with BERT payloads, but other payload types can exceed the maximum
size as well.
This patch truncates the payload if needed. It is better to receive
a truncated report than none.
=> klog_scanner.c: truncate payload if needed

configure.ac
Increase the version to 2.3.2 to reflect the fact that
bertprobe was entirely removed. The bertprobe functionality
was moved to klogscanner.
=> configure.ac: bump version

src/telemctl.c
The function "concatargs" allocated a buffer for concatenated strings
that was 1 byte short of needed, not accounting for the terminating
NULL char.
=> telemctl.c: fix buffer overflow

src/probes/crash_probe.c
process_corefile may be called twice due to retry logic.
Make sure frame_counter is initialized each time.
=> crash_probe.c: process_corefile: reset frame counter

src/telempostdaemon.c, src/telempostdaemon.h, tests/check_postd.c
Fixes issue #97 where the first record after `telemctl restart` is not inserted in journal.
=> Journal missing log

src/telemetry.c
- tm_set_payload: check payload for NULL value before duplication, this is desirable due the use of strnlen and strndup.
- tm_set_payload: replace strlen with strnlen to use MAX_PAYLOAD_LENGTH during function call instead of checking after the fact. And truncate read string if is > MAX_PAYLOAD_LENGTH.
=> telemetry.c: improvements
