- src/probes/telem_record_gen.c
Signed-off-by: John Andersen <john.s.andersen@intel.com>
> Validation for classification to ensure 2 slashes

- docs/man/telemd.1
- docs/man/telemd.1.rst
- missing static machine id (FILES section)
- wrong ref to config file
> Docs: fix two issues

- src/probes/crash_probe.c
- src/probes/journal.c
- src/probes/telem_record_gen.c
The bulk of the changes are converting to use getopt_long() instead of the GOptionContext API.
> Glib removal round 3

- .travis.yml
- README.md
- configure.ac
- src/local.mk
- src/probes/local.mk
- src/probes/pstore_probe.c
- tests/local.mk
This series finishes the required work to remove the glib dependency and using libnica instead.
> Finish glib removal

- src/probes/crash_probe.c
- src/probes/telem_record_gen.c
This series includes some miscellaneous cleanups to the code.
> Misc fixes

- src/probes/journal.c
Because log messages from services contain arbitrary data, and sometimes
this data is privacy sensitive, only enable the log level filters when
the privacy filter override is in effect.
> journal probe: conditionally enable log level filters

- scripts/telemctl
This set of commits:
- Triggers creation of telemetry daemon working directories, which are required by the daemon for proper functioning.
- Adds the is-active option to check if the daemon is active or inactive
- Removes telemetry daemon working folders.
> telemctl improvements

- src/data/bert-probe.service.in
- src/data/local.mk
- src/probes/bert_probe.c
- src/probes/local.mk
Telemetry probe to report Boot Error Region Table if such entry exists
in /sys/firmware/acpi/tables/
> BERT record probe

- src/common.c
- src/common.h
- src/local.mk
- src/probes/telem_record_gen.c
- src/telemetry.c
- src/telemetry.h
- src/telemetry.sym
- tests/check_daemon.c
- tests/check_libtelemetry.c
This header allows to group records by event_id.
> Support for event id header

- .travis.yml
- Makefile.am
- scripts/telemctl
- src/common.h
- src/journal/cli.c
- src/journal/journal.c
- src/journal/journal.h
- src/journal/local.mk
- src/local.mk
- src/main.c
- src/probes/telem_record_gen.c
- src/telemdaemon.c
- src/telemdaemon.h
- src/telemetry.c
- src/util.c
- src/util.h
- tests/check_journal.c
- tests/check_libtelemetry.c
- tests/local.mk
On this change:
- A basic journaling feature to telemetry daemon to keep track (locally in a system) of records that have been reported to telemetry server.
- Tests for new feature.
- Refactored event id tests.
> Telem journal

- src/data/telemetrics-dirs.conf.in
Adding entry to template for journal directory
Signed-off-by: avjarami <alex.v.jaramillo@intel.com>
> journal dir creation

- .gitignore
- src/journal/cli.c
- src/journal/journal.c
- src/telemetry.c
* Adding items to gitignore
* Removing ```gen_event_id``` and reusing ```get_random_id`` in util.c
* Fixing double free and memory leak
> House keeping and memory leak fixes

- src/common.h
- src/configuration.c
- src/configuration.h
- src/data/example.1.conf
- src/data/local.mk
- src/data/telemetrics-dirs.conf.in
- src/data/telemetrics.conf.in
- src/journal/cli.c
- src/journal/journal.c
- src/journal/journal.h
- src/local.mk
- src/main.c
- src/probes/telem_record_gen.c
- src/retention.c
- src/retention.h
- src/telemdaemon.c
- src/telemdaemon.h
- tests/check_config.c
- tests/check_journal.c
This change adds the ability to configure the telemetry daemon to save a copy of reported records locally.
> Record retention changes 

- src/probes/hello.c
1. Use stderr to print error messages
2. Rename the label 'fail' to 'done' as even non-failing code falls through the label
3. Consistently use EXIT_FAILURE/EXIT_SUCCESS, code sometimes used 1/0 instead.
4. free memory allocated via asprintf
5. Declare print_usage as 'static'
> hello.c: various tweaks

- src/probes/bert_probe.c
The original code "allocate_payload_buffer" returned 0 if "malloc" failed
and 1 if "malloc" succeeded. The "bertprobe" used this return value upon
exit. However "bertprobe" return code 0 corresponds to EXIT_SUCCESS
and return code 1 corresponds to EXIT_FALURE.
Similarily, "nc_b64enc_filename" returns 1 upon success and 0 upon
failure, so if the function fails, "bertprobe" exits with EXIT_SUCCESS.
To fix this, simplify the code and return with -ENOMEM immediately if memory
allocation fails and explicitly set return value to EXIT_FAILURE if
"nc_b64enc_filename" returns 0.
While at it, rename the label "fail" to "done" as this is common cleanup
exit code for both EXIT_SUCCESS and EXIT_FAILURE.
> bert_probe.c: don't return EXIT_SUCCESS in case of a failure

- src/data/hprobe.service.in
Also report locale and uptime.
> heartbeat: modified payload

- src/probes/telem_record_gen.c
1. Declare all local routines as static
2. Added support for custom config files (implemented the option "-f")
3. bugfix: -P option with non existing file would not fail.
4. More stringent parsing of classification, avoid hard coded numbers,
use pre-defined constants from "common.h" instead.
Also detect MAX_SUBCAT_LENGTH violation.
5. Some local routines were declared as "bool" instead of "int":
These routines used to return 1 if successful and 0 if failed.
This was confusing as all API routines return 0 upon success
and non-zero value if error.
6. Replaced the whole routine "allocate_payload_buffer" with a single
call to "calloc".
> telem_record_gen: various changes

- src/telempostdaemon.c
The 'else if (retry_attempt == MAX_RETRY_ATTEMPTS)' section would get
hit the first time through the loop on every invokation, printing the
failed to deliver error to the journal.
To fix it, initialize retry_attempt to zero and check that we're above
zero retries to enter retry sections.
> telempostdaemon: fix retries loop

- src/telemetry.c
This allows differentiation of different variants of an operating
system.
> telemetry.c: support variants in the OS header

- src/journal/cli.c
No functional changes.
Provide additional info in the usage message, based on user feedback.
While in there, some additional minor changes..
> telem_journal: improve usage message

- src/probes/crash_probe.c
A simple program that is highly recursive (or very deeply nested)
and causes stack overflow or segmentation fault can take hours
for crash_probe to process.
This patch fixes this by limiting the size of the stacktrace to 64.
The payload will also contain a corresponding message:
"Too many frames. Bactrace truncated".
> crash_probe: Limit the size of backtrace

- src/iorecord.c
> iorecord.c: fix memory allocation check

- src/nica/inifile.c
Don't assume calloc cannot fail, test the return value.
> inifile.c: Check for NULL pointer

- src/telemctl.c
Folders owned by "telemetry" may contain files that are not
owned by "telemetry". Allow deleting those.
> telemctl.c: allow deleting of files not owned by telemetry

- src/journal/journal.c
open_journal: Fix leaked file pointer on error exits.
print_journal: Make sure we always call free_journal_entry(entry),
regardless if we print the entry or not.
> journal.c: fix some resource leaks

- src/telemctl.c
Simplified the code for telemctl_opt_out and telemctl_opt_in.
There is no real need to call "access" to determine if opted_out
file exists, we get the same info by scrutinizing the errno.
This fixes any potential TOCTOU problems between access/create and access/unlink.
> telemctl.c: changed handling of opt_in/opt_out

- src/telemdaemon.c
handle_client: added a reasonable sanity check for record size.
Currently it is not possible to get max size of headers, so
the assumption is each line in header will be at most 80 chars.
> telemdaemon.c: sanity check for record size

- configure.ac
Version bump to reflect changes in the package.
> configure.ac: bump version to 2.2.3

- README.md
- docs/man/telemctl.1
- docs/man/telemctl.1.rst
- docs/man/telemetry.3
- docs/man/telemetry.3.rst
- src/common.h
- src/data/bert-probe.service.in
- src/data/hprobe.service.in
- src/data/hprobe.timer
- src/data/journal-probe-tail.service.in
- src/data/journal-probe.service.in
- src/data/pstore-probe.service.in
- src/data/telempostd.path.in
- src/data/telempostd.service.in
- src/data/telemprobd.service.in
- src/data/telemprobd.socket.in
- src/local.mk
- src/telemctl.c
- src/telemetry.c
- src/telemetry.h
- src/telemetry.sym
- tests/check_libtelemetry.c
Change to use explicit opt-in and documentation update to note the change.
> Require opt in

- .github/workflows/ccpp.yml
> Add github actions CI.

- src/data/hprobe.timer
Adding a 6 hour time window random value to probe timer.
> random shift to hprobe timer

- src/data/klogscanner.service.in
> Don't try to start the klogscanner service inside a container

- configure.ac
- src/local.mk
- src/telempostdaemon.c
- tests/local.mk
Use json document to transfer mesages to telemetry server.
> Convert api to json

- configure.ac
Replace clear text record format with json to transmit records to telemetry collector.
> configure.ac: bump version

- .github/workflows/ccpp.yml
- Use latest version of checkout action.
- Checkout the head of the PR commit.
> Update github action

- Makefile.am
Update the license file name in Makefile.am
> Use correct license file name in make dist

- src/journal/journal.c
- src/probes/hello.c
- src/spool.c
- src/telempostdaemon.c
* Potential resource leak.
* TOCTOU mitigation.
* Proper handling of return codes.
* Copy null terminator from source.
> Static analysis fixes

- src/iorecord.c
- src/journal/journal.c
* Insure body is null terminated.
* Add missing free.
> static analysis fixes 1
